#!/bin/sh

if [ $(git diff HEAD --name-only | wc -l) != 0 ]; then
    echo There are uncommitted changes. Refusing to add tag.
    exit 1
fi

version=$(awk -F= '/version=/ {print $2}' setup.py | sed 's/"//g' | sed 's/,//g')
tag=pytest-tcpclient-${version}

git tag -a ${tag} -m ${tag}
git push origin ${tag}
