#!/bin/sh

set -eu

if [ $(git branch --show-current) != "main" ]; then
    echo 'Not on branch "main". Refusing to add tag.'
    exit 1
fi

if [ $(git diff HEAD --name-only | wc -l) != 0 ]; then
    echo There are uncommitted changes. Refusing to add tag.
    exit 1
fi

# Make sure that .github/README.rst is up-to-date. If it isn't it will
# be generated and there will be uncommitted changes, which the next step
make readme

if [ $(git diff HEAD --name-only | wc -l) != 0 ]; then
    git commit -a -m "Regenerated github README"
fi

tag=$(awk -F= '/version = / {print $2}' pyproject.toml | sed 's/"//g' | sed 's/ //g')
echo tag=${tag}

git tag -a ${tag} -m ${tag}
git push origin --all
git push origin --tags
